# Generated by Django 5.1.1 on 2024-11-23 17:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Superadmin')], default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('inicio', models.CharField(max_length=100)),
                ('final', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('tipo', models.IntegerField()),
                ('limite', models.FloatField(null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('recovery_token', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('precio_base', models.FloatField()),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dni_frontal', models.ImageField(upload_to='solicitudes/dni/')),
                ('dni_reversa', models.ImageField(upload_to='solicitudes/dni/')),
                ('carnet_frontal', models.ImageField(upload_to='solicitudes/carnet/')),
                ('carnet_reversa', models.ImageField(upload_to='solicitudes/carnet/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elimapass.adminusuario')),
                ('codigo_tarjeta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime(2024, 11, 23, 17, 30, 49, 121797, tzinfo=datetime.timezone.utc))),
                ('monto_recargado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(max_length=50)),
                ('codigo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.usuario'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_hora', models.DateTimeField()),
                ('precio_final', models.FloatField()),
                ('bus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elimapass.bus')),
                ('codigo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarjeta')),
                ('id_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='ParaderoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido_ida', models.BooleanField(default=True)),
                ('id_paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.paradero')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.ruta')),
            ],
            options={
                'unique_together': {('id_ruta', 'id_paradero')},
            },
        ),
    ]
