# Generated by Django 5.1.1 on 2024-11-23 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0002_alter_recarga_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recarga',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 19, 39, 22, 606441, tzinfo=datetime.timezone.utc)),
        ),
    ]
