# Generated by Django 5.1.1 on 2024-11-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0009_paradero_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='final',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='inicio',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
