# Generated by Django 5.1.1 on 2024-11-23 02:42

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0010_ruta_final_ruta_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='bus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elimapass.bus'),
        ),
        migrations.AlterField(
            model_name='recarga',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 2, 42, 45, 359498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dni_frontal', models.ImageField(upload_to='solicitudes/dni/')),
                ('dni_reversa', models.ImageField(upload_to='solicitudes/dni/')),
                ('carnet_frontal', models.ImageField(upload_to='solicitudes/carnet/')),
                ('carnet_reversa', models.ImageField(upload_to='solicitudes/carnet/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('codigo_tarjeta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarjeta')),
            ],
        ),
    ]
