# Generated by Django 5.1.1 on 2024-11-23 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0011_tarjeta_fecha_vencimiento_viaje_bus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recarga',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 17, 12, 1, 219394, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('codigo_tarjeta',), name='unique_codigo_tarjeta_pendiente'),
        ),
    ]
